spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:derby:/{DBパス}/demo.db
    username: demo
    password:
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    hikari:
      mazimum-pool-size: 3
      minimum-idle: 1
