spring:
  #main:
    #banner-mode: off refs #47

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:derby:/mnt/hdd500/home/yasuokatou/develop/workspaces/DBs/yksTicketDB
    username: yksTicket
    password:
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    hikari:
      mazimum-pool-size: 3
      minimum-idle: 1
      